version: '3.6'

services:
  app:
    build: .
    depends_on:
      - db
    links:
      - "db:database"
    networks:
      - default
    restart: always
    ports:
      - 8080:8080

  db:
    environment:
      POSTGRES_USER: etl
      POSTGRES_PASSWORD: etl
      POSTGRES_DB: etl
    image: postgres:latest
    networks:
      - default
    ports:
      - 5432:5432
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data