version: '3.6'

services:
  air-flow:
    build: .
    depends_on:
      - db
    links:
      - "db:database"
    networks:
      - etl-network
    restart: always
    ports:
      - 8080:8080
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock

  db:
    environment:
      POSTGRES_USER: etl
      POSTGRES_PASSWORD: etl
      POSTGRES_DB: etl
    image: postgres:latest
    networks:
      - etl-network
    ports:
      - 5432:5432
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

networks:
  etl-network:
   name: etl-network